version: '3'

services:
  mongodb:
    image:  mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-prod:/data/db
    env_file: ./config/prodaction.env
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prodaction
    ports:
      - 80:80
    env_file: ./config/prodaction.env
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prodaction
    ports:
      - 5000:5000
    env_file: ./config/prodaction.env
    depends_on:
    - mongodb
volumes:
  mongo-prod: